#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "readarr"
name = "Readarr"
description.en = "Book Manager and Automation (Sonarr for Ebooks)"
description.fr = "Gestionnaire de livres et automatisation (Sonarr pour livres électroniques)"

version = "0.4.18.2805~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://readarr.com/"
admindoc = "https://wiki.servarr.com/readarr/installation/linux"
code = "https://github.com/Readarr/Readarr"
fund = "https://opencollective.com/readarr"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/readarr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://github.com/Readarr/Readarr/releases/download/v0.4.18.2805/Readarr.develop.0.4.18.2805.linux-core-x64.tar.gz"
        amd64.sha256 = "842ab11fac4f2e103e57badeaac1e2d44636b14dc727a1123098a2597adc5141"
        arm64.url = "https://github.com/Readarr/Readarr/releases/download/v0.4.18.2805/Readarr.develop.0.4.18.2805.linux-core-arm64.tar.gz"
        arm64.sha256 = "ecda47df6b6410e615c9fc0806af4b08a028d0843521e8587ca8beaa20737fca"
        armhf.url = "https://github.com/Readarr/Readarr/releases/download/v0.4.18.2805/Readarr.develop.0.4.18.2805.linux-core-arm.tar.gz"
        armhf.sha256 = "19db2a83b03935c1de829f06d1d1af936da69a5e13aaabd9c7947bfee49c3d51"
        i386.url = "https://github.com/Readarr/Readarr/releases/download/v0.4.18.2805/Readarr.develop.0.4.18.2805.linux-core-x86.tar.gz"
        i386.sha256 = "08038f06551f348e7dade028923dabd0fe6024c4e93a05adedb7265c3bb9dc7c"
        
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^Readarr.develop.*linux-core-x64.tar.gz$"
        autoupdate.asset.arm64 = "^Readarr.develop.*linux-core-arm64.tar.gz$"
        autoupdate.asset.armhf = "^Readarr.develop.*linux-core-arm.tar.gz$"
        autoupdate.asset.i386 = "^Readarr.develop.*linux-core-x86.tar.gz$"
        autoupdate.allow_prereleases = true

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 8787

    [resources.apt]
    packages = "sqlite3, curl"
